* Stokastisk Rapportgenerator (F# port)

Den stokastiske rapportgenerator så dagens lys i 1996 og har siden levet hos sin forfatter, [[Peter Sestoft][https://www.itu.dk/people/sestoft/]], på

https://www.itu.dk/people/sestoft/center.html

Hvis du ikke er stødt på dette fænomen før er der en glimrende artikel om den stokastiske rapport generator hos [[https://aktuelnaturvidenskab.dk/fileadmin/Aktuel_Naturvidenskab/nr-3/AN3-2014bagside.pdf][Aktuel Naturvidenskab.]]

Som det fremgår af ovenstående har rapportgeneratoren siden 2013 været hostet på en Raspberry Pi.
Jeg tror endda jeg engang har set denne stikke ud af en bogreol på Peters kontor.
Desværre er det ikke længere muligt at trykke "Bestil Forslag" og få hul igennem til rapportgeneratoren.
Det må nødvendigvis have haft en alt-ødelæggende effekt på antallet af bevillinger til nye virtuelle centre.
Derfor har det også ansporet mig til at færdiggøre et projekt jeg startede tilbage i 2012-13 stykker: At oversætte den stokastiske rapportgenerator, fra sit oprindelige MoscowML til F#.
Jeg er glad for at kunne meddele at projektet nu er fuldført, og at det igen er muligt at bestille nye forslag til
virtuelle centre, blot ved at trykke [[https://rapportrunner.azurewebsites.net/api/bestilrapport][Bestil Forslag]].

Johan Sivertsen, Oktober 2024

* Om oversættelsen

Jeg har forsøgt at holde mig så vidt muligt til originalteksten.
Den væsentligste afvigelse er at jeg har indført et nyt modul til at tegne lagkage og kurve-diagrammerne med SVG. Jeg har baseret mine figurer på billedet fra [[https://aktuelnaturvidenskab.dk/fileadmin/Aktuel_Naturvidenskab/nr-3/AN3-2014bagside.pdf][Aktuel Naturvidenskab.]] og på min hukommelse.
Denne afvigelse skyldes at de oprindelige diagrammer blev tegnet af et php-bibliotek og jeg havde meget mere lyst til at skrive mine egne end forsøge at få en php-server  op at stå.
Bortset fra dette har jeg også været nød til at brug færrer og værrer special-operatorer, da F# bare ikke har den samme muligheder her (som ex. en `||$*` operator), som med MoscowML.
Ligeledes har F# heller ikke en indbygget ``before`` operator, men den har jeg blot indført som nødvendigt.

Den oprindelige kildekode findes fortsat på linket ovenfor.
MoscowML koden er forsynet i toppen med:

#+begin_quote
(* Copyright 1996 Peter Sestoft.  
   Må kopieres og modificeres jvfr. GNU General Public License *)
#+end_quote

Hvilket jeg har søgt at leve op til ved også at angive `GNU General Public License` på dette projekt.

* TODO TODO
- Oversæt Dato format funktionen.
- Der er pt. en bug i seeding af tilfældigheds generatoren, så to rapporter med samme seed er ikke helt ens.
